services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mypro.wsgi:application
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mypro.settings
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: DATABASE_URL
        sync: false
    autoDeploy: true

databases:
  - name: my-django-db
    plan: free
    region: oregon
    postgresVersion: 14